apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-secured-infra
  title: Terraform – Secured Infra (VPC, S3)
  description: Scaffold a Terraform module for VPC + S3 with encryption.
spec:
  owner: platform-team
  type: infrastructure

  parameters:
    - title: Infrastructure Details
      required: [project_name, aws_region, vpc_cidr, s3_bucket_name]
      properties:

          - id: fetch
            name: Fetch Terraform Template
            action: fetch:template
            input:
              url: ./skeleton
              values:
                project_name: ${{ parameters.project_name }}
                aws_region: ${{ parameters.aws_region }}
                vpc_cidr: ${{ parameters.vpc_cidr }}
                s3_bucket_name: ${{ parameters.s3_bucket_name }}
                instancetype:
                  type: string
                  title: Select the compute requirement (t2.micro/t3.micro)
                  description: Compute type of the VM
                  enum:
                    - t2.micro
                    - t3.micro

          - id: repoExists
            name: Check if GitHub Repo Exists
            action: github:repoExists
            input:
              repoUrl: github.com?owner=RaviKumarPuneti-personal&repo=${{ parameters.project_name }}-infra

          - id: publish
            name: Publish to GitHub
            action: publish:github
            if: "!steps.repoExists.output.exists"
            input:
              repoUrl: github.com?owner=RaviKumarPuneti-personal&repo=${{ parameters.project_name }}-infra
              repoVisibility: private
              defaultBranch: main

          - id: register
            name: Register Infra in Backstage Catalog
            action: catalog:register
            input:
              repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
          

  steps:
    - id: fetch
      name: Fetch Terraform Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          project_name: ${{ parameters.project_name }}
          aws_region: ${{ parameters.aws_region }}
          vpc_cidr: ${{ parameters.vpc_cidr }}
          s3_bucket_name: ${{ parameters.s3_bucket_name }}
          instancetype: ${{ parameters.instancetype }}
        

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: github.com?owner=RaviKumarPuneti-personal&repo=${{ parameters.project_name }}-infra
        repoVisibility: public
    - id: wait
      name: Wait for GitHub to catch up
      action: debug:wait
      input:
        seconds: 5    
    - id: deregister
      name: Deregister Infra from Backstage Catalog
      action: catalog:deregister
      input:
        entityRef: ${{ parameters.project_name }}-infra

    - id: register
      name: Register Infra in Backstage Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
